export const motionRoleTaxonomy = {
  leadership: [
    "Founder / Leadership",
    "Potential Team Member",
    "Consultant",
    "Freelancer",
    "Adviser",
    "Board / Trustee Candidate",
    "Foundation Governance",
    "Strategic Adviser"
  ],
  ambassadors: [
    "Brand Ambassador",
    "Foundation Ambassador",
    "Athlete Ambassador",
    "Creator",
    "Influencer",
    "Public Speaker",
    "Author",
    "Journalist",
    "Broadcaster",
    "Presenter",
    "Podcaster",
    "Celebrity",
    "Campaigner",
    "Advocate",
    "Community Voice"
  ],
  disabilityCommunity: [
    "Disability Advocate",
    "Accessibility Expert",
    "Lived Experience Adviser",
    "Disability Organisation",
    "Community Leader",
    "Disability Employee Network Leader",
    "Disability Rights",
    "Accessibility Policy",
    "Inclusive Employment",
    "Independent Living",
    "Mobility",
    "Wheelchair Community",
    "Neurodiversity",
    "Sensory Disability",
    "Hidden Disability"
  ],
  sport: [
    "Paralympian",
    "Para Athlete",
    "Adaptive Athlete",
    "Sports Governing Body",
    "Coach",
    "Performance Professional",
    "Sports Marketing",
    "Sports Partnerships",
    "Sports Charity",
    "Sports Media",
    "Grassroots Sport"
  ],
  productDesign: [
    "Adaptive Fashion",
    "Inclusive Fashion",
    "Activewear",
    "Fashion Designer",
    "Product Designer",
    "Industrial Designer",
    "Inclusive Design",
    "Accessibility Research",
    "User Research",
    "Product Tester",
    "Apparel Technology",
    "Materials",
    "Manufacturing",
    "Sourcing"
  ],
  charitiesFoundation: [
    "Charity Partner",
    "Potential Foundation Partner",
    "Spinal Injury Charity",
    "Disability Charity",
    "Sports Charity",
    "Medical Research Charity",
    "Community Organisation",
    "Grant Maker",
    "Foundation",
    "Philanthropist",
    "Fundraiser",
    "CSR / ESG",
    "Social Impact"
  ],
  commercial: [
    "Brand Partner",
    "Sponsor",
    "Retail Partner",
    "Distribution",
    "Licensing",
    "Corporate Partner",
    "Employer Partner",
    "Procurement",
    "Partnerships",
    "Marketing",
    "Communications",
    "HR / People",
    "DEI",
    "Employee Benefits",
    "Insurance",
    "Healthcare",
    "Mobility",
    "Automotive",
    "Hospitality",
    "Travel",
    "Property",
    "Technology"
  ],
  mediaStorytelling: [
    "Filmmaker",
    "Production",
    "Photographer",
    "Editor",
    "Journalist",
    "Broadcaster",
    "Podcast",
    "Publisher",
    "Media Organisation",
    "PR",
    "Social Creator",
    "Creative Agency",
    "Disability-led Agency"
  ],
  fundingGrowth: [
    "Investor",
    "Angel",
    "Venture Capital",
    "Impact Investor",
    "Grant Maker",
    "Philanthropy",
    "Corporate Foundation",
    "Fundraiser",
    "Sponsorship",
    "Commercial Adviser"
  ],
  connectors: [
    "Warm Introducer",
    "Network Connector",
    "Corporate Connector",
    "Athlete Connector",
    "Charity Connector",
    "Media Connector",
    "Celebrity Connector",
    "Investor Connector",
    "International Connector"
  ]
} as const;

export const allMotionRoles = Object.values(motionRoleTaxonomy).flat();

export const relationshipWarmthLevels = [
  "HOT",
  "WARM",
  "KNOWN",
  "LIGHT",
  "CONNECTED",
  "COLD",
  "UNKNOWN"
] as const;

export const humanLearningStates = [
  "SHORTLIST",
  "INTERESTING",
  "NOT_RELEVANT",
  "WRONG_ROLE",
  "HOLD",
  "APPROACH",
  "CONTACTED",
  "ACTIVE_RELATIONSHIP",
  "PARTNER",
  "AMBASSADOR",
  "ADVISER",
  "DO_NOT_CONTACT"
] as const;
